<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Login test failed and refer E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-40.png]]>
    </line>
    <line>
      <![CDATA[<img src="file:///E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-40.png" alt=""/>]]>
    </line>
    <line>
      <![CDATA[Login test failed and refer E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-47.png]]>
    </line>
    <line>
      <![CDATA[<img src="file:///E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-47.png" alt=""/>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="21053" started-at="2020-11-13T17:26:27 IST" finished-at="2020-11-13T17:26:48 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21053" started-at="2020-11-13T17:26:27 IST" finished-at="2020-11-13T17:26:48 IST">
      <class name="tests.FBLoginTestDataProvider">
        <test-method status="PASS" signature="launchSite()[pri:1, instance:tests.FBLoginTestDataProvider@1f57539]" name="launchSite" duration-ms="7003" started-at="2020-11-13T17:26:27 IST" finished-at="2020-11-13T17:26:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchSite -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:tests.FBLoginTestDataProvider@1f57539]" name="loginTest" duration-ms="6938" started-at="2020-11-13T17:26:34 IST" data-provider="testdata" finished-at="2020-11-13T17:26:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[codecontributors123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[lank]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.FBLoginTestDataProvider.loginTest(FBLoginTestDataProvider.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login test failed and refer E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-40.png]]>
            </line>
            <line>
              <![CDATA[<img src="file:///E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-40.png" alt=""/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:tests.FBLoginTestDataProvider@1f57539]" name="loginTest" duration-ms="6946" started-at="2020-11-13T17:26:41 IST" data-provider="testdata" finished-at="2020-11-13T17:26:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[codecontributors123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nageswararao]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[nvalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.FBLoginTestDataProvider.loginTest(FBLoginTestDataProvider.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login test failed and refer E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-47.png]]>
            </line>
            <line>
              <![CDATA[<img src="file:///E:\Automation\AutomationNested\com.tddtestng.gui.facebook\13-Nov-2020-05-26-47.png" alt=""/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="closeSite()[pri:3, instance:tests.FBLoginTestDataProvider@1f57539]" name="closeSite" duration-ms="76" started-at="2020-11-13T17:26:48 IST" finished-at="2020-11-13T17:26:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSite -->
      </class> <!-- tests.FBLoginTestDataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
